Fix 'No annotation exists' error message.
Previously, accessing an annotation that doesn't exist threw a confusing
TypeError. Example:
```python
rasp.tokens.annotations["foo"]
```

Previously this raised
```
TypeError: list expected at most 1 argument, got 2
```

After this commit it raises
```
KeyError: "No annotation exists for key 'foo'. Available keys: {'name', 'encoding'}"
```